version: '3.8'

services:
  ortus:
    container_name: ortus
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '80:8080'
      - '5000:5000'