#!/usr/bin/bash

echo "# This file can be re-generated by running \".setup.sh\"" > .env

echo "VUE_APP_TITLE=\"ORTUS\"" >> .env

echo "Please submit mode [development/production] :"
read -r MODE
{
  echo "NODE_ENV=\"$MODE\""
  echo "FLASK_ENV=\"$MODE\""
} >> .env

{
  echo "SECRET_KEY=\"$(openssl rand -hex 50)\""
  echo "SECRET_VALIDATION_KEY=\"$(openssl rand -hex 50)\""
} >> .env

if [ "$MODE" == "development" ]
then
  {
    echo "BASIC_AUTH_USERNAME=\"admin\""
    echo "BASIC_AUTH_PASSWORD=\"admin\""
    echo "VUE_APP_BASE=\"http://localhost\""
    echo "APP_API_PORT=\"5000\""
    echo "APP_UI_PORT=\"8080\""
  } >> .env
elif [ "$MODE" == "production" ]
then
  {
    echo "BASIC_AUTH_USERNAME=\"$(openssl rand -hex 5)\""
    echo "BASIC_AUTH_PASSWORD=\"$(openssl rand -hex 5)\""
  } >> .env
else
  exit 1
fi

if [ "$MODE" == "production" ]
then
  echo "Please submit VUE_APP_BASE_URL :"
  read -r VUE_APP_BASE_URL
  echo "VUE_APP_BASE=\"$VUE_APP_BASE_URL\"" >> .env
elif [ "$MODE" == "development" ]
then
  pass
else
  exit 1
fi

echo "Please submit MAILGUN_API_KEY :"
read -r MAILGUN_API_KEY
echo "MAILGUN_API_KEY=\"$MAILGUN_API_KEY\"" >> .env

echo "Please submit MAILGUN_DOMAIN_NAME :"
read -r MAILGUN_DOMAIN_NAME
echo "MAILGUN_DOMAIN_NAME=\"$MAILGUN_DOMAIN_NAME\"" >> .env
