"""initial commit

Revision ID: 46acc3f887e8
Revises: 
Create Date: 2020-09-01 19:58:40.962241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "46acc3f887e8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "password",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("encrypted_password", sa.String(length=140), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_password_encrypted_password"),
        "password",
        ["encrypted_password"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_timestamp"), "password", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_password_timestamp"), table_name="password")
    op.drop_index(op.f("ix_password_encrypted_password"), table_name="password")
    op.drop_table("password")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
